apiVersion: v1
kind: Service
metadata: 
  name: demopods-nodeport
  namespace: default
spec:
  type: NodePort
  selector: 
    app: demopods
  ports: 
    - name: web
      port: 80
      targetPort: web
      nodePort: 31111
