apiVersion: apps/v1
kind: Deployment
metadata:
  name: labelled-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: labelled-deployment
  template:
    metadata:
      labels:
        app: labelled-deployment
    spec:
      containers:
      - name: labelled-deployment
        image: amitgujar/cloudmigration:latest
        ports:
        - containerPort: 80
      nodeSelector:
        hardware: high-spec
